image:
  file: .gitpod.Dockerfile

# Example tasks you might run once Gitpod is up:
tasks:
  - name: Build Debug APK
    command: ./gradlew assembleDebug

  - name: Build Release APK
    command: ./gradlew assembleRelease
